export const accord402ReadAbi = [
  {
    type: "function",
    name: "getCovenant",
    stateMutability: "view",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "exists", type: "bool" },
          { name: "covenantId", type: "uint64" },
          { name: "buyer", type: "address" },
          { name: "provider", type: "address" },
          { name: "buyerSettlementRecipient", type: "address" },
          { name: "providerSettlementRecipient", type: "address" },
          { name: "fundedAmount", type: "uint256" },
          { name: "outstandingAmount", type: "uint256" },
          { name: "providerSettlement", type: "uint256" },
          { name: "buyerSettlement", type: "uint256" },
          { name: "state", type: "string" },
          { name: "serviceSpecHash", type: "bytes32" },
          { name: "evidencePolicyHash", type: "bytes32" },
          { name: "openedAt", type: "uint64" },
          { name: "acceptanceDeadline", type: "uint64" },
          { name: "deliveryDeadline", type: "uint64" },
          { name: "challengeDuration", type: "uint64" },
          { name: "absoluteDisputeDeadline", type: "uint64" },
          { name: "evidenceRepairWindow", type: "uint64" },
          { name: "reviewRetryWindow", type: "uint64" },
          { name: "maxReviewGenerations", type: "uint32" },
          { name: "maxEvidenceAge", type: "uint64" },
          { name: "requiredCorroborationCount", type: "uint32" },
          { name: "repairAllowedFieldMask", type: "uint32" },
          { name: "replayScope", type: "string" },
          { name: "acceptedAt", type: "uint64" },
          { name: "deliveredAt", type: "uint64" },
          { name: "challengeDeadline", type: "uint64" },
          { name: "challengedAt", type: "uint64" },
          { name: "repairDeadline", type: "uint64" },
          { name: "retryDeadline", type: "uint64" },
          { name: "closedAt", type: "uint64" },
          { name: "deliveryPayload", type: "string" },
          { name: "deliveryHash", type: "bytes32" },
          { name: "activeEvidenceSetHash", type: "bytes32" },
          { name: "repairAuthorizationGeneration", type: "uint32" },
          { name: "repairAuthorizationActive", type: "bool" },
          { name: "challengeClaim", type: "string" },
          { name: "reviewGeneration", type: "uint32" },
          { name: "adjudicationDecision", type: "string" },
          { name: "failureClassification", type: "string" },
          { name: "closureReason", type: "string" },
          { name: "settlementDirection", type: "string" },
          { name: "settlementClaimed", type: "bool" },
        ],
      },
    ],
  },
] as const;

export const accord402RegistryReadAbi = [
  {
    type: "function",
    name: "getCriterionCount",
    stateMutability: "view",
    inputs: [
      { name: "core", type: "address" },
      { name: "covenantId", type: "uint64" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getCriterionPacked",
    stateMutability: "view",
    inputs: [
      { name: "core", type: "address" },
      { name: "covenantId", type: "uint64" },
      { name: "index", type: "uint256" },
    ],
    outputs: [{ name: "", type: "string" }],
  },
] as const;

export const accord402WriteAbi = [
  {
    type: "function",
    name: "retryReview",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimSettlement",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "authorizeUnchallengedSettlement",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "expireUnaccepted",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "expireNonDelivery",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "expireRepair",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "expireReview",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "challengeDelivery",
    stateMutability: "nonpayable",
    inputs: [
      { name: "covenantId", type: "uint64" },
      { name: "challengeClaim", type: "string" },
      { name: "challengedCriterionIds", type: "string[]" },
    ],
    outputs: [],
  },
] as const;
