export const accord402ReadAbi = [
  {
    type: "function",
    name: "getCovenant",
    stateMutability: "view",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "exists", type: "bool" },
          { name: "covenantId", type: "uint64" },
          { name: "buyer", type: "address" },
          { name: "provider", type: "address" },
          { name: "buyerSettlementRecipient", type: "address" },
          { name: "providerSettlementRecipient", type: "address" },
          { name: "fundedAmount", type: "uint256" },
          { name: "outstandingAmount", type: "uint256" },
          { name: "providerSettlement", type: "uint256" },
          { name: "buyerSettlement", type: "uint256" },
          { name: "state", type: "string" },
          { name: "serviceSpecHash", type: "bytes32" },
          { name: "evidencePolicyHash", type: "bytes32" },
          { name: "openedAt", type: "uint64" },
          { name: "acceptanceDeadline", type: "uint64" },
          { name: "deliveryDeadline", type: "uint64" },
          { name: "challengeDuration", type: "uint64" },
          { name: "absoluteDisputeDeadline", type: "uint64" },
          { name: "evidenceRepairWindow", type: "uint64" },
          { name: "reviewRetryWindow", type: "uint64" },
          { name: "maxReviewGenerations", type: "uint32" },
          { name: "maxEvidenceAge", type: "uint64" },
          { name: "requiredCorroborationCount", type: "uint32" },
          { name: "repairAllowedFieldMask", type: "uint32" },
          { name: "replayScope", type: "string" },
          { name: "acceptedAt", type: "uint64" },
          { name: "deliveredAt", type: "uint64" },
          { name: "challengeDeadline", type: "uint64" },
          { name: "challengedAt", type: "uint64" },
          { name: "repairDeadline", type: "uint64" },
          { name: "retryDeadline", type: "uint64" },
          { name: "closedAt", type: "uint64" },
          { name: "deliveryPayload", type: "string" },
          { name: "deliveryHash", type: "bytes32" },
          { name: "activeEvidenceSetHash", type: "bytes32" },
          { name: "repairAuthorizationGeneration", type: "uint32" },
          { name: "repairAuthorizationActive", type: "bool" },
          { name: "challengeClaim", type: "string" },
          { name: "reviewGeneration", type: "uint32" },
          { name: "adjudicationDecision", type: "string" },
          { name: "failureClassification", type: "string" },
          { name: "closureReason", type: "string" },
          { name: "settlementDirection", type: "string" },
          { name: "settlementClaimed", type: "bool" },
        ],
      },
    ],
  },
] as const;

export const accord402RegistryReadAbi = [
  {
    type: "function",
    name: "getCriterionCount",
    stateMutability: "view",
    inputs: [
      { name: "core", type: "address" },
      { name: "covenantId", type: "uint64" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getCriterionPacked",
    stateMutability: "view",
    inputs: [
      { name: "core", type: "address" },
      { name: "covenantId", type: "uint64" },
      { name: "index", type: "uint256" },
    ],
    outputs: [{ name: "", type: "string" }],
  },
] as const;

export const accord402VaultAbi = [
  {
    type: "function",
    name: "is_registered_payout",
    stateMutability: "view",
    inputs: [{ name: "recipient", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "begin_payout_registration",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "confirm_payout_registration",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
] as const;

export const accord402WriteAbi = [
  {
    type: "function",
    name: "openCovenant",
    stateMutability: "payable",
    inputs: [
      {
        name: "terms",
        type: "tuple",
        components: [
          { name: "provider", type: "address" },
          { name: "principal", type: "uint256" },
          { name: "serviceSpec", type: "string" },
          { name: "acceptanceDeadline", type: "uint64" },
          { name: "deliveryDeadline", type: "uint64" },
          { name: "challengeDuration", type: "uint64" },
          { name: "absoluteDisputeDeadline", type: "uint64" },
          { name: "evidenceRepairWindow", type: "uint64" },
          { name: "reviewRetryWindow", type: "uint64" },
          { name: "maxReviewGenerations", type: "uint32" },
          { name: "maxEvidenceAge", type: "uint64" },
          { name: "requiredCorroborationCount", type: "uint32" },
          { name: "repairAllowedFieldMask", type: "uint32" },
          { name: "replayScope", type: "string" },
          {
            name: "criteria",
            type: "tuple[]",
            components: [
              { name: "criterionId", type: "string" },
              { name: "criterionText", type: "string" },
            ],
          },
          {
            name: "authorityBindings",
            type: "tuple[]",
            components: [
              { name: "authorityId", type: "string" },
              { name: "authorityRevision", type: "uint32" },
              { name: "role", type: "string" },
              { name: "identityKind", type: "string" },
              { name: "identityValue", type: "string" },
              { name: "canonicalOrigin", type: "string" },
            ],
          },
        ],
      },
      { name: "buyerSettlementRecipient", type: "address" },
    ],
    outputs: [{ name: "covenantId", type: "uint64" }],
  },
  {
    type: "function",
    name: "acceptCovenant",
    stateMutability: "nonpayable",
    inputs: [
      { name: "covenantId", type: "uint64" },
      { name: "providerSettlementRecipient", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submitDelivery",
    stateMutability: "nonpayable",
    inputs: [
      { name: "covenantId", type: "uint64" },
      { name: "deliveryPayload", type: "string" },
      {
        name: "evidence",
        type: "tuple[]",
        components: [
          { name: "evidenceId", type: "string" },
          { name: "authorityId", type: "string" },
          { name: "authorityRevision", type: "uint32" },
          { name: "subject", type: "string" },
          { name: "kind", type: "string" },
          { name: "sourceKind", type: "string" },
          { name: "canonicalSource", type: "string" },
          { name: "immutableVersionOrRecordId", type: "string" },
          { name: "publishedAt", type: "uint64" },
          { name: "observedAt", type: "uint64" },
          { name: "expiresAt", type: "uint64" },
          { name: "contentDigest", type: "bytes32" },
          { name: "isPrimary", type: "bool" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submitEvidenceRepair",
    stateMutability: "nonpayable",
    inputs: [
      { name: "covenantId", type: "uint64" },
      {
        name: "replacements",
        type: "tuple[]",
        components: [
          { name: "replacesEvidenceId", type: "string" },
          { name: "evidenceId", type: "string" },
          { name: "authorityId", type: "string" },
          { name: "authorityRevision", type: "uint32" },
          { name: "subject", type: "string" },
          { name: "kind", type: "string" },
          { name: "sourceKind", type: "string" },
          { name: "canonicalSource", type: "string" },
          { name: "immutableVersionOrRecordId", type: "string" },
          { name: "publishedAt", type: "uint64" },
          { name: "observedAt", type: "uint64" },
          { name: "expiresAt", type: "uint64" },
          { name: "contentDigest", type: "bytes32" },
          { name: "isPrimary", type: "bool" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "retryReview",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimSettlement",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "authorizeUnchallengedSettlement",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "expireUnaccepted",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "expireNonDelivery",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "expireRepair",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "expireReview",
    stateMutability: "nonpayable",
    inputs: [{ name: "covenantId", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "challengeDelivery",
    stateMutability: "nonpayable",
    inputs: [
      { name: "covenantId", type: "uint64" },
      { name: "challengeClaim", type: "string" },
      { name: "challengedCriterionIds", type: "string[]" },
    ],
    outputs: [],
  },
] as const;
